package com.webtoapp.core.engine

import android.app.Activity
import android.app.AlertDialog
import android.graphics.Typeface
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.BaseAdapter
import android.widget.ListView
import android.widget.TextView
import com.webtoapp.core.i18n.Strings
import com.webtoapp.core.logging.AppLogger
import org.mozilla.geckoview.GeckoResult
import org.mozilla.geckoview.GeckoSession

internal data class GeckoChoiceDialogRow(
    val choice: GeckoSession.PromptDelegate.ChoicePrompt.Choice?,
    val label: String,
    val selectable: Boolean,
    val selected: Boolean,
    val groupLabel: Boolean = false,
    val separator: Boolean = false
)

/**
 * Converts Gecko's hierarchical select model into rows suitable for an Android ListView.
 * Group labels and separators remain visible but non-selectable, and a disabled optgroup
 * disables all of its descendants.
 */
internal fun flattenGeckoChoiceRows(
    choices: Array<out GeckoSession.PromptDelegate.ChoicePrompt.Choice>
): List<GeckoChoiceDialogRow> = buildList {
    fun appendChoices(
        source: Array<out GeckoSession.PromptDelegate.ChoicePrompt.Choice>,
        depth: Int,
        parentDisabled: Boolean
    ) {
        source.forEach { choice ->
            val indent = "\u2003".repeat(depth)
            when {
                choice.separator -> add(
                    GeckoChoiceDialogRow(
                        choice = null,
                        label = "$indent────────────",
                        selectable = false,
                        selected = false,
                        separator = true
                    )
                )

                choice.items != null -> {
                    val hasLabel = choice.label.isNotEmpty()
                    if (hasLabel) {
                        add(
                            GeckoChoiceDialogRow(
                                choice = null,
                                label = "$indent${choice.label}",
                                selectable = false,
                                selected = false,
                                groupLabel = true
                            )
                        )
                    }
                    appendChoices(
                        source = choice.items!!,
                        depth = if (hasLabel) depth + 1 else depth,
                        parentDisabled = parentDisabled || choice.disabled
                    )
                }

                else -> add(
                    GeckoChoiceDialogRow(
                        choice = choice,
                        label = "$indent${choice.label}",
                        selectable = !parentDisabled && !choice.disabled,
                        selected = choice.selected
                    )
                )
            }
        }
    }

    appendChoices(choices, depth = 0, parentDisabled = false)
}

/** Completes GeckoView ChoicePrompt requests generated by HTML select controls. */
internal object GeckoChoicePromptDialog {
    private const val TAG = "GeckoChoicePrompt"

    fun show(
        activity: Activity?,
        prompt: GeckoSession.PromptDelegate.ChoicePrompt
    ): GeckoResult<GeckoSession.PromptDelegate.PromptResponse> {
        if (activity == null || activity.isFinishing || activity.isDestroyed) {
            return GeckoResult.fromValue(prompt.dismiss())
        }

        val result = GeckoResult<GeckoSession.PromptDelegate.PromptResponse>()
        var completed = false
        fun finish(response: GeckoSession.PromptDelegate.PromptResponse) {
            if (!completed) {
                completed = true
                result.complete(response)
            }
        }

        activity.runOnUiThread {
            try {
                if (activity.isFinishing || activity.isDestroyed) {
                    finish(prompt.dismiss())
                    return@runOnUiThread
                }

                val rows = flattenGeckoChoiceRows(prompt.choices)
                if (rows.isEmpty()) {
                    finish(prompt.dismiss())
                    return@runOnUiThread
                }

                val choiceMode: Int
                val choiceRowLayout: Int
                when (prompt.type) {
                    GeckoSession.PromptDelegate.ChoicePrompt.Type.MENU -> {
                        choiceMode = ListView.CHOICE_MODE_NONE
                        choiceRowLayout = android.R.layout.select_dialog_item
                    }

                    GeckoSession.PromptDelegate.ChoicePrompt.Type.SINGLE -> {
                        choiceMode = ListView.CHOICE_MODE_SINGLE
                        choiceRowLayout = android.R.layout.select_dialog_singlechoice
                    }

                    GeckoSession.PromptDelegate.ChoicePrompt.Type.MULTIPLE -> {
                        choiceMode = ListView.CHOICE_MODE_MULTIPLE
                        choiceRowLayout = android.R.layout.select_dialog_multichoice
                    }

                    else -> {
                        AppLogger.w(TAG, "Unsupported ChoicePrompt type: ${prompt.type}")
                        finish(prompt.dismiss())
                        return@runOnUiThread
                    }
                }

                val listView = ListView(activity).apply {
                    this.choiceMode = choiceMode
                    adapter = GeckoChoiceAdapter(activity, rows, choiceRowLayout)
                }
                val selected = BooleanArray(rows.size) { rows[it].choice != null && rows[it].selected }
                var selectedIndex = rows.indices.firstOrNull { selected[it] } ?: -1

                if (choiceMode != ListView.CHOICE_MODE_NONE) {
                    selected.forEachIndexed { index, checked ->
                        if (checked) listView.setItemChecked(index, true)
                    }
                }

                val builder = AlertDialog.Builder(activity).setView(listView)
                prompt.title?.takeIf { it.isNotBlank() }?.let { builder.setTitle(it) }
                prompt.message?.takeIf { it.isNotBlank() }?.let { builder.setMessage(it) }

                when (prompt.type) {
                    GeckoSession.PromptDelegate.ChoicePrompt.Type.MENU -> {
                        builder.setNegativeButton(Strings.btnCancel) { _, _ ->
                            finish(prompt.dismiss())
                        }
                    }

                    GeckoSession.PromptDelegate.ChoicePrompt.Type.SINGLE -> {
                        builder
                            .setPositiveButton(Strings.confirm) { _, _ ->
                                val choice = rows.getOrNull(selectedIndex)?.choice
                                finish(if (choice == null) prompt.dismiss() else prompt.confirm(choice.id))
                            }
                            .setNegativeButton(Strings.btnCancel) { _, _ ->
                                finish(prompt.dismiss())
                            }
                    }

                    GeckoSession.PromptDelegate.ChoicePrompt.Type.MULTIPLE -> {
                        builder
                            .setPositiveButton(Strings.confirm) { _, _ ->
                                val selectedIds = rows.indices
                                    .filter { selected[it] }
                                    .mapNotNull { rows[it].choice?.id }
                                    .toTypedArray()
                                finish(prompt.confirm(selectedIds))
                            }
                            .setNegativeButton(Strings.btnCancel) { _, _ ->
                                finish(prompt.dismiss())
                            }
                    }
                }

                builder.setOnCancelListener { finish(prompt.dismiss()) }
                val dialog = builder.create()

                listView.setOnItemClickListener { _, _, position, _ ->
                    val row = rows[position]
                    val choice = row.choice
                    if (!row.selectable || choice == null) return@setOnItemClickListener

                    when (prompt.type) {
                        GeckoSession.PromptDelegate.ChoicePrompt.Type.MENU -> {
                            finish(prompt.confirm(choice.id))
                            dialog.dismiss()
                        }

                        GeckoSession.PromptDelegate.ChoicePrompt.Type.SINGLE -> {
                            selectedIndex = position
                        }

                        GeckoSession.PromptDelegate.ChoicePrompt.Type.MULTIPLE -> {
                            selected[position] = listView.isItemChecked(position)
                        }
                    }
                }

                dialog.show()
            } catch (e: Exception) {
                AppLogger.w(TAG, "ChoicePrompt dialog failed: ${e.message}")
                finish(prompt.dismiss())
            }
        }

        return result
    }
}

private class GeckoChoiceAdapter(
    activity: Activity,
    private val rows: List<GeckoChoiceDialogRow>,
    private val choiceRowLayout: Int
) : BaseAdapter() {
    private val inflater = LayoutInflater.from(activity)

    override fun getCount(): Int = rows.size

    override fun getItem(position: Int): GeckoChoiceDialogRow = rows[position]

    override fun getItemId(position: Int): Long = position.toLong()

    override fun areAllItemsEnabled(): Boolean = false

    override fun isEnabled(position: Int): Boolean = rows[position].selectable

    override fun getViewTypeCount(): Int = 2

    override fun getItemViewType(position: Int): Int = if (rows[position].choice == null) 1 else 0

    override fun getView(position: Int, convertView: View?, parent: ViewGroup): View {
        val row = rows[position]
        val layout = if (row.choice == null) android.R.layout.simple_list_item_1 else choiceRowLayout
        val view = convertView ?: inflater.inflate(layout, parent, false)
        val text = view.findViewById<TextView>(android.R.id.text1)
        text.text = row.label
        text.isEnabled = row.selectable
        text.alpha = if (row.selectable) 1f else 0.55f
        text.typeface = if (row.groupLabel) Typeface.DEFAULT_BOLD else Typeface.DEFAULT
        text.gravity = if (row.separator) {
            android.view.Gravity.CENTER
        } else {
            android.view.Gravity.START or android.view.Gravity.CENTER_VERTICAL
        }
        view.isEnabled = row.selectable
        return view
    }
}
